version: 2
jobs:
  build:
    docker:
      - image: circleci/php:8.1-nginx
    steps:
      - checkout
      - run:
          name: Build and test PHP application
          command: |
            set -x
            php -v
            php -S localhost:8080 -t .
